### ISSUE TITLE
ESPresense Companion Crashes when ANY devices are tracked.

### ISSUE THREAD

**Issue by benscammell** [ESPresense/ESPresense-companion#570]
WORKS....

```
# Devices to track
devices:
   - id: "node:*"`
```

CRASHES....

```
# Devices to track
devices:
  - name: "*"
  - id: "node:*"`
```

LOG

```
[23:13:34 INF] Now listening on: http://[::]:8267
[23:13:34 INF] Application started. Press Ctrl+C to shut down.
[23:13:34 INF] Hosting environment: Production
[23:13:34 INF] Content root path: /App
[23:13:35 ERR] BackgroundService failed
SQLite.SQLiteException: database disk image is malformed
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.Insert(Object obj)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass50_0.<InsertAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ESPresense.Models.DeviceHistoryStore.Add(DeviceHistory dh) in /App/src/Models/DeviceHistory.cs:line 46
   at ESPresense.Controllers.GlobalEventDispatcher.OnDeviceChanged(Device device) in /App/src/Controllers/GlobalEventDispatcher.cs:line 21
   at ESPresense.Locators.MultiScenarioLocator.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Locators/MultiScenarioLocator.cs:line 76
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[23:13:35 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
SQLite.SQLiteException: database disk image is malformed
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.Insert(Object obj)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass50_0.<InsertAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ESPresense.Models.DeviceHistoryStore.Add(DeviceHistory dh) in /App/src/Models/DeviceHistory.cs:line 46
   at ESPresense.Controllers.GlobalEventDispatcher.OnDeviceChanged(Device device) in /App/src/Controllers/GlobalEventDispatcher.cs:line 21
   at ESPresense.Locators.MultiScenarioLocator.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Locators/MultiScenarioLocator.cs:line 76
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[23:13:35 INF] Application is shutting down...
```

PLEASE HELP...

**Comment by cyrano1966** [comment]
Exactly the same problem here. Not sure if related but in my case, problem appeared after a restore from HA backups due to a faulty SD crash. 
I attempted almost everything: switch off and removal of all espresense devices, deleting all references via MQTT Explorer and reinstall of the Companion Add On.
Espresense works ok, detecting fingerprints of devices, but as soon as any type of device is added to config yaml, Companion add on crashes with the logs as above.
Is this a DB problem on HA DB or Mosquito dB? Is there any way to completely clean up Companion and reinstall?

**Comment by cyrano1966** [comment]
Problem solved on my side. Removed Add-on Companion. Saved /config/espresense/config.yaml in different folder for reuse. Deleted full /config/espresense folder (removing hidden .storage folder inside, which contains history file). Reinstalled Companion Add-on. Recreated /config/espresense and moved back config.yaml. Started Add-on
After that, it has been working for one hour without crashing
