### ISSUE TITLE
managedMqttClient error prevents startup.

### ISSUE THREAD

**Issue by chrisgilldc** [ESPresense/ESPresense-companion#593]
I had to restore my Home Assistant installation after a failure and am now unable to start ESPresense-Companion. I've tried reinstalling it several times.

I get the following in the logs on startup.

`[21:20:16 INF] Loading /config/espresense/config.yaml
[21:20:17 INF] Optimization enabled
[21:20:17 INF] Attempting to connect to mqtt server at core-mosquitto:1883 as addons...
[21:20:17 ERR] Hosting failed to start
System.ArgumentNullException: Value cannot be null. (Parameter 'managedMqttClient')
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClientExtensions.EnqueueAsync(IManagedMqttClient managedMqttClient, String topic, String payload, MqttQualityOfServiceLevel qualityOfServiceLevel, Boolean retain)
   at ESPresense.Services.MqttCoordinator.EnqueueAsync(String topic, String payload, Boolean retain) in /App/src/Services/MqttCoordinator.cs:line 198
   at ESPresense.Services.TelemetryService.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/TelemetryService.cs:line 50
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[21:20:17 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeSettingsStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeSettingsStore.cs:line 62
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeTelemetryStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeTelemetryStore.cs:line 35
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeTelemetryStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeTelemetryStore.cs:line 35
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeSettingsStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeSettingsStore.cs:line 62
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 INF] Application is shutting down...
[21:20:17 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.DeviceSettingsStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/DeviceSettingsStore.cs:line 35
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.DeviceSettingsStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/DeviceSettingsStore.cs:line 35
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Locators.DeviceTracker.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Locators/DeviceTracker.cs:line 91
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[21:20:17 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Locators.DeviceTracker.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Locators/DeviceTracker.cs:line 91
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'managedMqttClient')
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClientExtensions.EnqueueAsync(IManagedMqttClient managedMqttClient, String topic, String payload, MqttQualityOfServiceLevel qualityOfServiceLevel, Boolean retain)
   at ESPresense.Services.MqttCoordinator.EnqueueAsync(String topic, String payload, Boolean retain) in /App/src/Services/MqttCoordinator.cs:line 198
   at ESPresense.Services.TelemetryService.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/TelemetryService.cs:line 50
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /App/src/Program.cs:line 110`

**Comment by WhoaLookAtThat** [comment]
chrisgilldc, I know it's not very helpful for you, but I have the same issue - after a restoration, ESPresense-Companion stopped working, reinstalling doesn't resolve it.

**Comment by chrisgilldc** [comment]
@WhoaLookAtThat Any chance you found a fix? I've tried providing a username and password but that's not sufficient to make it happy.

**Comment by BobiderBob** [comment]
I have the same problem

**Comment by colinhatfield** [comment]
I'm also having this issue

**Comment by chrisgilldc** [comment]
I was able to work around this by copying out my config, then wiping it entirely, uninstalling the add-on and reinstalling it. That appears to reset whatever voodoo happens on the backend to get the MQTT info in.

**Comment by micdis** [comment]
providing host (IP Adress) solved the problem for me!

**Comment by robertvorthman** [comment]
@micdis How do you provide the IP address? I don't see any place to configure the add-on.

**Comment by MasterDevwi** [comment]
I'm hitting the same issue. I was able to fix it a few months ago by completely removing and reinstalling ESPresense Companion (I didn't change any settings, but it magically started working again), but it's broken once again.

I tried adding my host IP and port, but now when ESPresence launches it seems to connect to MQTT but I'm getting a SQLite database disk image error. A full reinstall didn't resolve the issue either.

```
[14:49:12 ERR] BackgroundService failed
SQLite.SQLiteException: database disk image is malformed
   at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery(Object[] source)
   at SQLite.SQLiteConnection.Insert(Object obj, String extra, Type objType)
   at SQLite.SQLiteConnection.Insert(Object obj)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass50_0.<InsertAsync>b__0(SQLiteConnectionWithLock conn)
   at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1.<WriteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

@robertvorthman, you can add your IP address under espresense/config.yaml:

mqtt:
  host: <your IP address>
  port: 1883
  ssl: false
  username: <your user name>
  password:  <your password>

**Comment by nwithan8** [comment]
Not stale
