### ISSUE TITLE
Crashing after update to 1.0.15

### ISSUE THREAD

**Issue by USA-RedDragon** [ESPresense/ESPresense-companion#935]
I have this addon installed in Home Assistant, and after updating to 1.0.15, it crashes with the following stacktrace:

```
[10:59:58 INF] Loading /config/espresense/config.yaml
[10:59:59 INF] Optimization enabled
[10:59:59 INF] Attempting to connect to mqtt server at core-mosquitto:1883 as addons...
[10:59:59 ERR] Hosting failed to start
System.ArgumentNullException: Value cannot be null. (Parameter 'managedMqttClient')
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClientExtensions.EnqueueAsync(IManagedMqttClient managedMqttClient, String topic, String payload, MqttQualityOfServiceLevel qualityOfServiceLevel, Boolean retain)
   at ESPresense.Services.MqttCoordinator.EnqueueAsync(String topic, String payload, Boolean retain) in /App/src/Services/MqttCoordinator.cs:line 199
   at ESPresense.Services.TelemetryService.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/TelemetryService.cs:line 50
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[10:59:59 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeTelemetryStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeTelemetryStore.cs:line 32
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[10:59:59 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeSettingsStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeSettingsStore.cs:line 60
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
[10:59:59 FTL] The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at ESPresense.Services.NodeTelemetryStore.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/NodeTelemetryStore.cs:line 32
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'managedMqttClient')
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClientExtensions.EnqueueAsync(IManagedMqttClient managedMqttClient, String topic, String payload, MqttQualityOfServiceLevel qualityOfServiceLevel, Boolean retain)
   at ESPresense.Services.MqttCoordinator.EnqueueAsync(String topic, String payload, Boolean retain) in /App/src/Services/MqttCoordinator.cs:line 199
   at ESPresense.Services.TelemetryService.ExecuteAsync(CancellationToken stoppingToken) in /App/src/Services/TelemetryService.cs:line 50
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /App/src/Program.cs:line 110
```

**Comment by jpettitt** [comment]
+1

**Comment by kendadk** [comment]
+1

**Comment by RN-Say** [comment]
+1

**Comment by drrgriffiths** [comment]
I had the same problem, solved it by entering my mqtt host details in the espresence config.yaml. Works perfectly now
